### ISSUE TITLE
setPlayerState returns wrong HTTP status code

### ISSUE THREAD

**Issue by augustjanse** [hyperblast/beefweb#124]
`setPlayerState` states that its response is `200`, but in reality it is `204`.

Tested on latest development build.

#### Background
I noticed when trying to POST from [bravado](https://github.com/Yelp/bravado).

```
>>> client.player.setPlayerState(isMuted=False).response()
Traceback (most recent call last):
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado/http_future.py", line 267, in unmarshal_response
    op=operation,
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado/http_future.py", line 296, in unmarshal_response_inner
    response_spec = get_response_spec(status_code=response.status_code, op=op)
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado_core/response.py", line 154, in get_response_spec
    "status_code or use a `default` response.".format(status_code, op))
bravado_core.exception.MatchingResponseNotFound: Response specification matching http status_code 204 not found for operation Operation(setPlayerState). Either add a response specification for the status_code or use a `default` response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado/http_future.py", line 155, in response
    swagger_result = self._get_swagger_result(incoming_response)
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado/http_future.py", line 238, in _get_swagger_result
    self.request_config.response_callbacks,
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado/http_future.py", line 277, in unmarshal_response
    sys.exc_info()[2])
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado/http_future.py", line 267, in unmarshal_response
    op=operation,
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado/http_future.py", line 296, in unmarshal_response_inner
    response_spec = get_response_spec(status_code=response.status_code, op=op)
  File "/home/august/git/ha-beefweb/venv/lib/python3.6/site-packages/bravado_core/response.py", line 154, in get_response_spec
    "status_code or use a `default` response.".format(status_code, op))
bravado.exception.HTTPError: 204 No Content: Response specification matching http status_code 204 not found for operation Operation(setPlayerState). Either add a response specification for the status_code or use a `default` response.
```

**Comment by hyperblast** [comment]
Hi, thanks for reporting this.

Current swagger specification is somewhat incomplete.

It is provided mostly as a quick-and-dirty documentation, without attempt to make generate any code from it (I'm not a fan of auto-generated clients anyway).

**Comment by augustjanse** [comment]
Oh, I might have sent the PR a bit prematurely if I'm going to encounter more errors. I'll try the rest of the endpoints before sending another one. Thanks for the quick merge!

**Comment by hyperblast** [comment]
Any API endpoint could return error which not document in any way and likely would break as well.

Error response is the JSON as well with the following format:

````json
{
    "error": {
        "message": "some error message",
        "parameter": "request parameter that caused error (optional)"
    }
}
````
I've grep'd sources for possible error codes. At least the following are used: `400`, `401`, `403`, `405`, `500`

On success status code `200` or `204` is used depending on response body availability.
